// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.3

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type CustomerHTTPServer interface {
	CustomerStatus(context.Context, *CustomerStatusRequest) (*CustomerStatusReply, error)
}

func RegisterCustomerHTTPServer(s *http.Server, srv CustomerHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/status", _Customer_CustomerStatus0_HTTP_Handler(srv))
}

func _Customer_CustomerStatus0_HTTP_Handler(srv CustomerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CustomerStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/sentinel.job.v1.Customer/CustomerStatus")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CustomerStatus(ctx, req.(*CustomerStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CustomerStatusReply)
		return ctx.Result(200, reply)
	}
}

type CustomerHTTPClient interface {
	CustomerStatus(ctx context.Context, req *CustomerStatusRequest, opts ...http.CallOption) (rsp *CustomerStatusReply, err error)
}

type CustomerHTTPClientImpl struct {
	cc *http.Client
}

func NewCustomerHTTPClient(client *http.Client) CustomerHTTPClient {
	return &CustomerHTTPClientImpl{client}
}

func (c *CustomerHTTPClientImpl) CustomerStatus(ctx context.Context, in *CustomerStatusRequest, opts ...http.CallOption) (*CustomerStatusReply, error) {
	var out CustomerStatusReply
	pattern := "/v1/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/sentinel.job.v1.Customer/CustomerStatus"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
