// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/i6u/kratos-mono-layout/app/greeter/service/internal/biz"
	"github.com/i6u/kratos-mono-layout/app/greeter/service/internal/conf"
	"github.com/i6u/kratos-mono-layout/app/greeter/service/internal/data"
	"github.com/i6u/kratos-mono-layout/app/greeter/service/internal/server"
	"github.com/i6u/kratos-mono-layout/app/greeter/service/internal/service"
)

// Injectors from wire.go:

func initApp(registry *conf.Registry, confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(logger, confData)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(logger, dataData)
	greeterUseCase := biz.NewGreeterUseCase(logger, greeterRepo)
	greeterService := service.NewGreeterService(logger, greeterUseCase)
	httpServer := server.NewHTTPServer(logger, confServer, greeterService)
	grpcServer := server.NewGRPCServer(logger, confServer, greeterService)
	registrar, cleanup2 := server.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
