// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.3

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type GreeterHTTPServer interface {
	SayHi(context.Context, *SayHiRequest) (*SayHiReply, error)
}

func RegisterGreeterHTTPServer(s *http.Server, srv GreeterHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/hi/{name}", _Greeter_SayHi0_HTTP_Handler(srv))
}

func _Greeter_SayHi0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SayHiRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/greeter.service.v1.Greeter/SayHi")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SayHi(ctx, req.(*SayHiRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SayHiReply)
		return ctx.Result(200, reply)
	}
}

type GreeterHTTPClient interface {
	SayHi(ctx context.Context, req *SayHiRequest, opts ...http.CallOption) (rsp *SayHiReply, err error)
}

type GreeterHTTPClientImpl struct {
	cc *http.Client
}

func NewGreeterHTTPClient(client *http.Client) GreeterHTTPClient {
	return &GreeterHTTPClientImpl{client}
}

func (c *GreeterHTTPClientImpl) SayHi(ctx context.Context, in *SayHiRequest, opts ...http.CallOption) (*SayHiReply, error) {
	var out SayHiReply
	pattern := "/v1/hi/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/greeter.service.v1.Greeter/SayHi"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
