server:
  http:
    network: tcp
    address: 0.0.0.0:8000
    timeout: 1s
  grpc:
    network: tcp
    address: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    network: tcp
    address: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
registry:
  endpoint: 127.0.0.1:2379
  timeout: 1s